apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdb-mongodb-pvc
  namespace: egs-uniride
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi